### ISSUE TITLE
Switch Jetson and RoboRio to USB Communication

### ISSUE THREAD

**Issue by mlucas** [Tino-FRC-2473/FRC2019#6]
Historically, we have opened a TCP socket between the Jetson and RoboRio to send telemetry data from the Jetson. This has caused a high failure rate due to timeouts, races, etc.

We should consider moving to USB-CDC for communication between the two controllers. The RoboRio will act as the host (USB A) and the Jetson will be a device (USB Micro-B).

**Comment by mvoodarla** [comment]
https://github.com/Tino-FRC-2473/FRC2019/pull/10 should resolve this.

**Comment by mvoodarla** [comment]
Merged #10. Closing this.
